### ISSUE TITLE
first installation

### ISSUE THREAD

**Issue by smirnov-mi** [jp-gouin/helm-openldap#1]
k8s 1.6.2:

 helm install --name ldap helm-openldap/ --tls

Error: YAML parse error on openldap/charts/ltb-passwd/templates/ingress.yaml: error converting YAML to JSON: yaml: line 5: mapping values are not allowed in this context

I only changed storage-class and size in values.

Also setting both phpldapadmin and ltb-passwd to false:

Error: validation failed: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"        ( It's apps/v1 in k8s 1.6.2)

Having this done, the pods crashing (interesing enough - only two are visible) with 

read_config: no serverID / URL match found. Check slapd -h arguments

**Comment by kpc31** [comment]
Hi @smirnov-mi ,
Just updated the chart with the templatisation of api version to avoid this issue.
Now ltb-passwd isn't working well so you should disable it.

You don't need to pass `tls` argument, ldaps is already configured. This is only to pass a custom certificate.

So could you please retry without the `tls`and tell me if you have still the issue ?

**Comment by smirnov-mi** [comment]
Hi @kpc31 , 
the   --tls    refers to my HELM, so it's OK. I don't know how to tell helm to use tls by default, so I have to add "--tls" manually every time. 

I tried the updated chart now,
one little thing - I had to set  apps/v1  in the phpldapadmin/templates/deployment.yaml.

One big thing:    ldap pod still crashes, phpLDAPadmin crashes as well, logs below. Does it require some sort of initial ldif or something?

openldap container logs:
 
*** CONTAINER_LOG_LEVEL = 3 (info)
*** Search service in CONTAINER_SERVICE_DIR = /container/service :
*** link /container/service/:ssl-tools/startup.sh to /container/run/startup/:ssl-tools
*** link /container/service/slapd/startup.sh to /container/run/startup/slapd
*** link /container/service/slapd/process.sh to /container/run/process/slapd/run
*** Set environment for startup files
*** Environment files will be proccessed in this order :
Caution: previously defined variables will not be overriden.
/container/environment/99-default/default.yaml
/container/environment/99-default/default.startup.yaml

To see how this files are processed and environment variables values,
run this container with '--loglevel debug'
*** Running /container/run/startup/:ssl-tools...
*** Running /container/run/startup/slapd...
Database and config directory are empty...
Init new ldap server...
  Backing up /etc/ldap/slapd.d in /var/backups/slapd-2.4.47+dfsg-3~bpo9+1... done.
  Creating initial configuration... done.
  Creating LDAP directory... done.
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of restart.
Start OpenLDAP...
Waiting for OpenLDAP to start...
Add bootstrap schemas...
config file testing succeeded
Add image bootstrap ldif...
Add custom bootstrap ldif...
Add TLS config...
Add replication config...
Stop OpenLDAP...
Configure ldap client TLS configuration...
Remove config files...
First start is done...
*** Set environment for container process
*** Remove file /container/environment/99-default/default.startup.yaml
*** Environment files will be proccessed in this order :
Caution: previously defined variables will not be overriden.
/container/environment/99-default/default.yaml

To see how this files are processed and environment variables values,
run this container with '--loglevel debug'
*** Running /container/run/process/slapd/run...
5df6c98d @(#) $OpenLDAP: slapd  (Feb  9 2019 17:02:42) $
        Debian OpenLDAP Maintainers <pkg-openldap-devel@lists.alioth.debian.org>
5df6c98d read_config: no serverID / URL match found. Check slapd -h arguments.
5df6c98d slapd stopped.
5df6c98d connections_destroy: nothing to destroy.
*** /container/run/process/slapd/run exited with status 1
*** Killing all processes...

 
phpldapadmin container logs:
2019/12/16 00:07:45 [INFO] received CSR
2019/12/16 00:07:45 [INFO] generating key: ecdsa-384
2019/12/16 00:07:45 [INFO] encoded CSR
2019/12/16 00:07:45 [INFO] signed certificate with serial number 54607662596946035950657881504992111099161697437
Link /container/service/:ssl-tools/assets/default-ca/default-ca.pem to /container/service/ldap-client/assets/certs/ldap-ca.crt
*** Running /container/run/startup/phpldapadmin...
Set apache2 http config...
Bootstap phpLDAPadmin...
tr: write error: Broken pipe
tr: write error
sed: -e expression #1, char 79: unterminated `s' command
*** /container/run/startup/phpldapadmin failed with status 1

*** Killing all processes...

**Comment by kpc31** [comment]
Hi @smirnov-mi 

I think i found your issue, the chart has to be deployed in the chart name namespace, openldap in your case.
I'll investigate why .

I just updated the chart with phpldap running and ltb-passwd

**Comment by smirnov-mi** [comment]
Hey @kpc31 ,   thank you very much!  
Looks like it works now. Have to verify if the sync really works, but I see 3 pods and phpLDAPadmin as well.    I have a question: what is the LDAP-conf then with 3 masters ?  Do they have each two more servers configured, to sync with?    Or  does it make more sence to use only 2 pods, so they sync each other?      
 
I will enable ltb-passwd now and try it.

**Comment by kpc31** [comment]
Hi @smirnov-mi  , they all see eachother.
There are a variable configured `LDAP_REPLICATION_HOSTS`  for 3 hosts the variable looks like : 
```
#PYTHON2BASH:['ldap://helm-openldap-github-0.helm-openldap-github-headless','ldap://helm-openldap-github-1.helm-openldap-github-headless','ldap://helm-openldap-github-2.helm-openldap-github-headless']
```

If you need to scale up or down then you have to update the chart with the number of wanted replica.

The replication configuration is : 
```
LDAP_REPLICATION_CONFIG_SYNCPROV: "binddn=\"cn=admin,cn=config\" bindmethod=simple credentials=$LDAP_CONFIG_PASSWORD searchbase=\"cn=config\" type=refreshAndPersist retry=\"60 +\" timeout=1 "
  LDAP_REPLICATION_DB_SYNCPROV: "binddn=\"cn=admin,$LDAP_BASE_DN\" bindmethod=simple credentials=$LDAP_ADMIN_PASSWORD searchbase=\"$LDAP_BASE_DN\" type=refreshAndPersist interval=00:00:00:10 retry=\"60 +\" timeout=1 "
```
I will update the chart to add some info in the values , like the `interval` and the `timeout`

**Comment by smirnov-mi** [comment]
OK, cool. Sorry, i'm new to k8s and to multi-master ldap as well . 

ltb-passwd wouldn't start. Describe pod gives: 

    Environment:
      LDAP_SERVER:           ldaps://openldap.openldap
      LDAP_BINDDN:           <set to the key 'BINDDN' in secret 'openldap'>  Optional: false
      LDAP_BINDPASS:         <set to the key 'BINDPW' in secret 'openldap'>  Optional: false
      LDAP_STARTTLS:         false
      LDAP_BASE_SEARCH:      dc=example,dc=org
      SECRETEKEY:            LDAP_ADMIN_PASSWORD
      LDAP_LOGIN_ATTRIBUTE:  cn

Events:
  Type     Reason   Age                    From                     Message
  ----     ------   ----                   ----                     -------
  Warning  Failed   27m (x211 over 77m)    kubelet, worker-01  Error: couldn't find key BINDDN in Secret ldap/openldap

**Comment by kpc31** [comment]
Hi @smirnov-mi ,

Indeed you have to create two Key in the secret defined in `binduserSecret` .
Per defaults its `openldap` , so you have to add the Key `BINDDN` and `BINDPW`  to the dn of the user admin ans its password. 
Or any users allowed to query the database

**Comment by smirnov-mi** [comment]
I'm trying to do it, no luck yet....  Upgraded my HELM to v3 in the meanwhile...

**Comment by smirnov-mi** [comment]
Hi @jp-gouin , hope you're doing well.

I ended up having it installed somehow last time (2x openldap + phpLDAPadmin). Now I'm trying to recreate it and no luck. I also tried to increase number of replicas to 3 and the 3rd pod can not start as well. 
I'm on k8s 1.7.2 now.  Start of the first pod is always like this. (BTW it always starts with loglevel 3):

*** CONTAINER_LOG_LEVEL = 3 (info)
*** Search service in CONTAINER_SERVICE_DIR = /container/service :
*** link /container/service/:ssl-tools/startup.sh to /container/run/startup/:ssl-tools
*** link /container/service/slapd/startup.sh to /container/run/startup/slapd
*** link /container/service/slapd/process.sh to /container/run/process/slapd/run
*** Set environment for startup files
*** Environment files will be proccessed in this order :
Caution: previously defined variables will not be overriden.
/container/environment/99-default/default.startup.yaml
/container/environment/99-default/default.yaml

To see how this files are processed and environment variables values,
run this container with '--loglevel debug'
*** Running /container/run/startup/:ssl-tools...
*** Running /container/run/startup/slapd...
Database and config directory are empty...
Init new ldap server...
  Backing up /etc/ldap/slapd.d in /var/backups/slapd-2.4.48+dfsg-1~bpo10+1... done.
  Creating initial configuration... done.
  Creating LDAP directory... done.
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of restart.
Start OpenLDAP...
Waiting for OpenLDAP to start...
Add bootstrap schemas...
config file testing succeeded
Add image bootstrap ldif...
Add custom bootstrap ldif...
Add replication config...
Stop OpenLDAP...
Remove config files...
First start is done...
*** Set environment for container process
*** Remove file /container/environment/99-default/default.startup.yaml
*** Environment files will be proccessed in this order :
Caution: previously defined variables will not be overriden.
/container/environment/99-default/default.yaml

To see how this files are processed and environment variables values,
run this container with '--loglevel debug'
*** Running /container/run/process/slapd/run...
5e959d85 @(#) $OpenLDAP: slapd  (Jul 30 2019 16:24:19) $
        Debian OpenLDAP Maintainers <pkg-openldap-devel@lists.alioth.debian.org>
5e959d85 read_config: no serverID / URL match found. Check slapd -h arguments.
5e959d85 slapd stopped.
5e959d85 connections_destroy: nothing to destroy.
*** /container/run/process/slapd/run exited with status 1
*** Killing all processes...
