### ISSUE TITLE
Can we modify the root cn=config.

### ISSUE THREAD

**Issue by wynax** [jp-gouin/helm-openldap#107]
Hi,

I need to add some module, a policy password and change some configuration on cn=config. 

With customLdifFiles it's seem not working. 
Do we have a way to change the configuration ?

**Comment by jp-gouin** [comment]
Hi @wynax ,

you should add your configuration under `customAcls` , you have to keep the default config or something similar to keep `ltb-passwd` working .

you can also take a look at `customschemafiles` https://github.com/jp-gouin/helm-openldap/blob/master/.bin/myval.yaml if you want to add a schéma to support your config

**Comment by yuqo2450** [comment]
Hey,
I am also struggling with ACLs. I found out how to replace the 3 basic rules, but can't get more than those working.
It would be amazing if it was possible to get some insight to ACL management with this chart.

Moreover I tried to add the _rfc2307bis schema_, but couldn't get it to work. Just cause you mentioned it

Might be just me, because I am quite new to LDAP, so I would appreciate some feedback :)

**Comment by wynax** [comment]
hi,

For me it work fine, be carefull to the syntax.

Be aware that you must have in your configuration the global.bindDN or you can replace the value in your file. 
The ldif it's executed before the import of the Schema. 

So if your configuration need a specific schema be sure that you put the schema in your customAcls.

A exemple : 

```
customAcls: |-
 dn: olcDatabase={2}mdb,cn=config
 changetype: modify
 replace: olcAccess
 olcAccess: {0}to *
   by dn.exact=gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth manage
   by * break
 olcAccess: {1}to attrs=userPassword,shadowLastChange
   by self write
   by dn="cn=admin,dc=example,dc=org" write
   by anonymous auth by * none
 olcAccess: {2}to *
   by dn="cn=admin,dc=example,dc=org" write
   by self read
   by * none
 
 dn: olcDatabase={2}mdb,cn=config
 changetype: modify
 add: olcMonitoring
 olcMonitoring: TRUE
 
 dn: cn=module{0},cn=config
 changetype: modify
 add: olcModuleLoad
 olcModuleLoad: memberof
 
 dn: cn=module{0},cn=config
 changetype: modify
 add: olcModuleLoad
 olcModuleLoad: ppolicy
 
 dn: cn=module{0},cn=config
 changetype: modify
 add: olcModuleLoad
 olcModuleLoad: unique
 
 dn: olcDatabase={2}mdb,cn=config
 changetype: modify
 add: olcLastBind
 olcLastBind: TRUE
 
 
 # {1}memberof, {2}mdb, config
 dn: olcOverlay={1}memberof,olcDatabase={2}mdb,cn=config 
 changetype: add
 objectClass: olcOverlayConfig
 objectClass: olcConfig
 objectClass: olcMemberOf
 objectClass: top
 olcOverlay: {1}memberof
 olcMemberOfDangling: ignore
 olcMemberOfRefInt: TRUE
 olcMemberOfGroupOC: groupOfNames
 olcMemberOfMemberAD: member
 olcMemberOfMemberOfAD: memberOf
 
 # {2}ppolicy, {2}mdb, config
 dn: olcOverlay={2}ppolicy,olcDatabase={2}mdb,cn=config
 changetype: add
 objectClass: olcOverlayConfig
 objectClass: olcPPolicyConfig
 olcOverlay: {2}ppolicy
 olcPPolicyDefault: cn=password policy,ou=policies,dc=Alcatel
 olcPPolicyHashCleartext: TRUE
 olcPPolicyUseLockout: TRUE

 dn: cn=schemacustom,cn=schema,cn=config
 changetype: add
 olcObjectClasses: ( 1.3.12.2.1006.59.9.4.1.2 NAME 'testUser' DESC test
  custom user' SUP inetorgperson STRUCTURAL MUST ( registrationDate $ temporary
  Password ) MAY ( test ) )
 cn: schemacustom
 objectClass: olcSchemaConfig
 olcAttributeTypes: ( 1.3.12.2.1006.59.5.4.10 NAME 'test' DESC 'Company Id
  entifier' SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 SINGLE-VALUE )

 dn: olcOverlay=unique,olcDatabase={2}mdb,cn=config
 changetype: add
 olcUniqueAttribute: test
 olcOverlay: unique
 objectClass: olcOverlayConfig
 objectClass: olcUniqueConfig
```

**Comment by yuqo2450** [comment]
OK so if I get you right I should add custom schemas to the _customAcls_ key not the _customSchemaFiles_?

But I still don't understand how to add more than **3 ACLs** to the ldap config. Your example also only states **3 olcAccess** attributes and as soon as I add/replace more than those I have no access to the tree. (Including _cn=admin,dc=ldap,dc=homelab_).

Like I said, maybe I just don't understand the _ldif_ syntax, so would be amazing if you could give me a 4+ rule example.

**Comment by yuqo2450** [comment]
Found my mistakes. Works flawless now. Thanks for help @wynax and @jp-gouin!

**Comment by yuqo2450** [comment]
Sorry for reopening this, but I came to a point where I have to adjust the acl rules I had initially set up.
I haven't found a way to **update them in place**, meaning without uninstalling the chart and reinstalling it. If I try to update the acls with `ldapmodify` I get `ldap_modify: Insufficient access (50)`.
Is there a way?

**Comment by jp-gouin** [comment]
It only works on the first execution, after you need to use ldap directly to update your acls

**Comment by yuqo2450** [comment]
What do you mean with ldap directly?
Like I said `ldapmodify` doesn't seem to work.

**Comment by jp-gouin** [comment]
Inside the container run `ldapmodify -Y EXTERNAL -H "ldapi:///" -f <your.ldif>`
