### ISSUE TITLE
When i deploy completed, the log shows the following error, please help me

### ISSUE THREAD

**Issue by MrLiu94** [jp-gouin/helm-openldap#108]
647e88c5.2d28ba76 0x7f3275ffb700 slap_client_connect: URI=ldap://my-release-2.my-release-headless.ldap.svc.cluster.local:1389 Error, ldap_start_tls failed (2)
647e88c5.2d2aa7cd 0x7f3275ffb700 do_syncrepl: rid=003 rc 2 retrying

647e88cc.2cdbeb2b 0x7f3275ffb700 conn=15486 fd=12 ACCEPT from IP=10.244.1.1:50176 (IP=0.0.0.0:1389)
647e88cc.2cde2816 0x7f32777fe700 conn=15486 fd=12 closed (connection lost)

**Comment by jp-gouin** [comment]
Hi @MrLiu94 ,
Can you post the `values` your are using ? 
Is this the log of the first `openldap` container ?

**Comment by MrLiu94** [comment]
1.I use the default values, no customization
2.all of openldap pods return the same log,just from IP=xxx.xxx.xxx.xxx:xxxx is different

**Comment by jp-gouin** [comment]
Thanks , can you post the complete log from startup ?
