### ISSUE TITLE
Chart doesnt work as expected in default configuration

### ISSUE THREAD

**Issue by suresh-now** [jp-gouin/helm-openldap#109]
**Describe the bug**
 After installation, and exec into the pod,  the ldapsearch -x -b "dc=example,dc=org" -H ldap://0.0.0.0:1389, will return always return empty result. Only when env.LDAP_EXTRA_SCHEMAS: "cosine,inetorgperson,nis" is set, the chart works.

**To Reproduce**
1) Create  a values file
replicaCount: 1
replication:
  enabled: false
persistence:
  enabled: false
tls:
  enabled: false
ltb-passwd:
  enabled: false
phpldapadmin:
  enabled: false
2) helm install my-release -f values.yaml helm-openldap/openldap-stack-ha
3) kubectl exec -it my-release-0 /bin/bash 
4)  ldapsearch -x -b "dc=example,dc=org" -H ldap://0.0.0.0:1389
5) The default set of user are not returned

**Expected behavior**
The default users should be returned

**Desktop (please complete the following information):**
-Mac

**Comment by lucj** [comment]
@suresh-now Do you still have the problem ?

**Comment by r1cebank** [comment]
Just curious has anything changed in the chart version 4.1.1? My configuration has been working with v4.1.1 but recently following a redeployment of the same configs I am experiencing the same issue this person is reporting.
