### ISSUE TITLE
phpldapadmin "This base cannot be created with PLA" with replication enabled

### ISSUE THREAD

**Issue by clayrisser** [jp-gouin/helm-openldap#112]
How can I prevent the following error "This base cannot be created with PLA" while also still using replication.

I know this was address in #97, but the solution was basically to disable replication, which I cannot do because of my requirements.

**Comment by jp-gouin** [comment]
Hi @clayrisser 

Can you post your values file please?

**Comment by SamuelLHuber** [comment]
> Hi @clayrisser
> 
> Can you post your values file please?

happy to provide mine. I get sensible error messages without replication enabled and just the PLA thing with it disabled

also happy to arrange financial compensation for timespent getting this to work with openldap 2.6.6 + replication as we need it internally at our company
