### ISSUE TITLE
Support for additional LDAP managers

### ISSUE THREAD

**Issue by SuperQ** [jp-gouin/helm-openldap#121]
**Is your feature request related to a problem? Please describe.**

PHP LDAP Admin is nice and generic, but it's not as nice as a simple "Add User" UI.

**Describe the solution you'd like**

I was thinking it would be useful to support more specizlized account management.

Maybe one of these:
* [LDAP Account Manager](https://www.ldap-account-manager.org/)
* [LDAP Manager](https://github.com/romnn/ldap-manager)

**Describe alternatives you've considered**

Using external helm chart to deploy those tools.

**Additional context**

It would be nice to provide a nicer out-of-the-box experience for user management.

**Comment by jp-gouin** [comment]
Can you post a link to both helm chart to deploy those solution so I can evaluate them ?

**Comment by SuperQ** [comment]
I was thinking about just contributing the templates directly. I hadn't actually looked around for other charts yet.

**Comment by jp-gouin** [comment]
Sure thing ! I can see that ldap manager has already a container and the maintainer is planning a Helm chart

**Comment by SuperQ** [comment]
Note stale, just not had time to work on it.

**Comment by SuperQ** [comment]
still not stale, just no time to work on it.

**Comment by SuperQ** [comment]
Not stale

**Comment by SuperQ** [comment]
Still would be nice

**Comment by SuperQ** [comment]
Not stale
