### ISSUE TITLE
I hope to customize the openldap administrator user name when deploying

### ISSUE THREAD

**Issue by opencmit2** [jp-gouin/helm-openldap#122]
The default administrator user password of the openldap that is deployed through this chart package is admin. Our company requires that it be customized and we cannot use a fixed name.

**Comment by jp-gouin** [comment]
Hi @opencmit2 ,

Yes you should be able to set the admin name using `env. LDAP_ADMIN_USERNAME` variable 
Unfortunately by setting it to something else that `admin` replication will fail.

You can submit a PR to support the configuration of the admin username if you feeling it

**Comment by opencmit2** [comment]
Hi @jp-gouin  

I have tested and confirmed that there is no problem. I hope you can merge it as soon as possible after testing.

**Comment by jp-gouin** [comment]
@opencmit2 thanks for the contribution, can you sync your PR with the main branch -> the pipeline has been fixed and merged

**Comment by jp-gouin** [comment]
Closed PR #123
