### ISSUE TITLE
LDAP Replication Customization

### ISSUE THREAD

**Issue by baobabtr33** [jp-gouin/helm-openldap#133]
Problem Description:
I am trying to add additional olcServerID and olcSyncrepl for replication.
I want my LDAP servers to sync with another LDAP server that is in another cluster.
In order to do that, I need to be able to add  replication profile, yet adding values in "customSchemaFile" does not work?

How can I customize the replication LDIFS?

**Comment by zerowebcorp** [comment]
@baobabtr33  Did you figure it out? I am looking for the same.
