### ISSUE TITLE
Add annotations to ltb and phpldapadmin deployments

### ISSUE THREAD

**Issue by RamilMus** [jp-gouin/helm-openldap#139]
**Is your feature request related to a problem? Please describe.**
Add annotations to deployments of ltb and phpldapadmin
Wanted to use it to update release with 
annotations:
  secret.reloader.stakater.com/reload: secrets

**Describe the solution you'd like**
Add in templates annotations

**Comment by jp-gouin** [comment]
Indeed currently annotation is not available on those charts . Labels are only available on ltb.

would you like to submit a PR to add those supports ?
