### ISSUE TITLE
existingConfigmap not found in the chart

### ISSUE THREAD

**Issue by zerowebcorp** [jp-gouin/helm-openldap#140]
**Describe the bug**
The document says `existingConfigmap` is a valid option. However when trying to search for it in the chart, I don't see it anywhere. https://github.com/search?q=repo%3Ajp-gouin%2Fhelm-openldap+existingConfigmap&type=code

How do I inject custom ldif file to the pod without overriding anything? I am trying to figure out how to add a custom olcSyncrepl  block and inject into the pod so that I can manually ssh into the pod and apply it or let it apply during booting. I want my openldap to replicate to another openldap that is in another k8s cluster. `customLdifFiles` will override the default ldif files which is not what I want. I thought `existingConfigmap` might help. Or is there any other option?

**Comment by jp-gouin** [comment]
You might want to add your configuration under `customSchemaFiles ` which I think is more appropriate for your needs
