### ISSUE TITLE
Release tags do not align with chart versions

### ISSUE THREAD

**Issue by rkul** [jp-gouin/helm-openldap#17]
Hello Jean Philippe,

Release tags in this repo are a bit confusing. Usually they are represents helm chart versions.
What do you think about updating them to align with Chart versions?

Btw, [page on Artifacthub](https://artifacthub.io/packages/helm/helm-openldap/openldap) a bit outdated and confusing. I found that chart version is wrong and configuration part belongs to old release.

Please let me know if I can help!
Regards,
Roman

**Comment by jp-gouin** [comment]
Hi , on artifact hub this chart is outdated the new one is https://artifacthub.io/packages/helm/helm-openldap/openldap-stack-ha and is available when you click on the link of the readme .
You’re right the next tag should reflect the version of the chart.

**Comment by jp-gouin** [comment]
Release tag of latest version now matches the version of the charts
