### ISSUE TITLE
How to modify cn=config?

### ISSUE THREAD

**Issue by davidfrickert** [jp-gouin/helm-openldap#172]
**Is your feature request related to a problem? Please describe.**
I want to disable anonymous binds and unauthenticated binds without needing to run ldapmodify myself.
Ideally, i supply the LDIF files to the chart and it does it for me.
I tried to supply these via `customAcls` and `customLdifFiles`, none work though.

```
dn: cn=config
changetype: modify
add: olcDisallows
olcDisallows: bind_anon
```

```
dn: olcDatabase={-1}frontend,cn=config
changetype: modify
add: olcRequires
olcRequires: authc
```

From reading docs in this repo, modifying cn=config is not possible yet? What are the blockers? https://github.com/jp-gouin/helm-openldap/blob/78f801c07f6f6477e48fd3716bdbe105607d2ee9/README.md?plain=1#L284C1-L284C97

**Describe the solution you'd like**
The LDIF above can be added somewhere on values.yaml and are configured in the OpenLDAP cluster without manual effort (such as running ldapmodify).

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by davidfrickert** [comment]
Reading bitnami openldap docs and it seems that they have an env var for anon binds: `LDAP_ALLOW_ANON_BINDING`. Will check it out.

**Comment by davidfrickert** [comment]
I will create a separate issue to allow setting this env var via values.yaml

**Comment by jp-gouin** [comment]
Hi @davidfrickert ,

some old statement remaining in the doc I’m afraid. 

You absolutely can using `customSchemaFiles` which allows you to update `cn=config`

**Comment by davidfrickert** [comment]
thanks @jp-gouin
