### ISSUE TITLE
Is MenmberOf sample working?

### ISSUE THREAD

**Issue by josue-sanchez-wabtec** [jp-gouin/helm-openldap#180]
Hello community ,

Have make this example https://github.com/jp-gouin/helm-openldap/blob/master/advanced_examples/MemberOf.md work?

I am adding deploying my release with the values that this example suggest but I am still seeing same sample organization tree?

<img width="480" alt="image" src="https://github.com/user-attachments/assets/5703b8f2-6023-4aa7-a857-12e14727e1cb">

**Comment by jp-gouin** [comment]
Hi @josue-sanchez-wabtec 

Make sure you are starting from a fresh namespace or make sure you don't have any remaining `PV` for `openldap`. 

- Delete the chart
- Delete `pvc` in the namespace you installed the chart (make sure to target only `openldap` ones 
- or delete the namespace if it's only for `openldap`
- install the chart
