### ISSUE TITLE
additional info: olcPPolicyDefault: attribute type undefined

### ISSUE THREAD

**Issue by avodapalli2** [jp-gouin/helm-openldap#184]
Hi,

 I want to set the password policy for my ldap confiiguration so in old openldap with osixia image i was able to set it with `olcPPolicyDefault` but the newest helm chart with bitnami i get this error as olcPPolicyDefault: attribute type undefined.

Do you have any idea? I set  below envs 

 ```
 LDAP_CONFIGURE_PPOLICY: "yes"
  LDAP_PPOLICY_HASH_CLEARTEXT : "true"
  LDAP_PPOLICY_USE_LOCKOUT : "true"
```
and add custom acl as 
```
  dn: olcOverlay={0}ppolicy,olcDatabase={2}mdb,cn=config
  changetype: modify
  add: olcPPolicyDefault
  olcPPolicyDefault: cn=default,ou=pwpolicies,dc=skat-classic,dc=dxc,dc=com
```

**Comment by jp-gouin** [comment]
hi @avodapalli2 , it’s most likely you need to enable the module first , similar to :

```
# Load syncprov module
    dn: cn=module,cn=config
    cn: module
    objectClass: olcModuleList
    olcModuleLoad: syncprov.so
    olcModulePath: /opt/bitnami/openldap/lib/openldap
    ```

**Comment by jp-gouin** [comment]
Ok so the module should be loaded when setting `LDAP_CONFIGURE_PPOLICY: "yes"`

Inside the bitnami starting script:

```sh
ldap_configure_ppolicy() {
    info "Configuring LDAP ppolicy"
    ldap_load_module "/opt/bitnami/openldap/lib/openldap" "ppolicy.so"
    # create configuration
    cat > "${LDAP_SHARE_DIR}/ppolicy_create_configuration.ldif" << EOF
dn: olcOverlay={0}ppolicy,olcDatabase={2}mdb,cn=config
objectClass: olcOverlayConfig
objectClass: olcPPolicyConfig
olcOverlay: {0}ppolicy
EOF
    debug_execute ldapadd -Q -Y EXTERNAL -H "ldapi:///" -f "${LDAP_SHARE_DIR}/ppolicy_create_configuration.ldif"
    # enable ppolicy_hash_cleartext
    if is_boolean_yes "$LDAP_PPOLICY_HASH_CLEARTEXT"; then
        info "Enabling ppolicy_hash_cleartext"
        cat > "${LDAP_SHARE_DIR}/ppolicy_configuration_hash_cleartext.ldif" << EOF
dn: olcOverlay={0}ppolicy,olcDatabase={2}mdb,cn=config
changetype: modify
add: olcPPolicyHashCleartext
olcPPolicyHashCleartext: TRUE
EOF
    debug_execute ldapmodify -Q -Y EXTERNAL -H "ldapi:///" -f "${LDAP_SHARE_DIR}/ppolicy_configuration_hash_cleartext.ldif"
    fi
    # enable ppolicy_use_lockout
    if is_boolean_yes "$LDAP_PPOLICY_USE_LOCKOUT"; then
        info "Enabling ppolicy_use_lockout"
        cat > "${LDAP_SHARE_DIR}/ppolicy_configuration_use_lockout.ldif" << EOF
dn: olcOverlay={0}ppolicy,olcDatabase={2}mdb,cn=config
changetype: modify
add: olcPPolicyUseLockout
olcPPolicyUseLockout: TRUE
EOF
        debug_execute ldapmodify -Q -Y EXTERNAL -H "ldapi:///" -f "${LDAP_SHARE_DIR}/ppolicy_configuration_use_lockout.ldif"
    fi
}
```

I'm not seeing `olcPPolicyDefault` set in the `olcPpolicyConfig` created.

You could try to add the following schema : 

```
dn: olcOverlay={0}ppolicy,olcDatabase={2}mdb,cn=config
changetype: modify
add: olcPPolicyDefault
olcPPolicyDefault: cn=default,ou=pwpolicies,dc=skat-classic,dc=dxc,dc=com
```

**Comment by jp-gouin** [comment]
Hi @avodapalli2 

I investigated your issue and find out that `ldap_configure_ppolicy` function called inside the bitnami container is done after adding `ldap_add_custom_schema` . 

So basically adding a custom scheme with 
```
dn: olcOverlay={0}ppolicy,olcDatabase={2}mdb,cn=config
  changetype: modify
  add: olcPPolicyDefault
  olcPPolicyDefault: cn=default,ou=pwpolicies,dc=skat-classic,dc=dxc,dc=com
``` 

Will fail because the module is not yet enabled and configured. 

I tried to manually add the `olcPPolicyDefault` and it worked (however without the `ou=pwpolicies`  you probably need to create the ou first) 

Anyway, you have 3 options 
1. You open a ticket on Bitnami side and asked for `ldap_configure_ppolicy` to contain the `olcPPolicyDefault ` parameter
2. You open a ticket on Bitnami side and asked for `ldap_configure_ppolicy` to be executed before calling `ldap_add_custom_schema`
3.  You enable the module only using the chart and not the env var. You'll have to add the same `ldif` as 
```sh
ldap_configure_ppolicy() {
    info "Configuring LDAP ppolicy"
    ldap_load_module "/opt/bitnami/openldap/lib/openldap" "ppolicy.so"
    # create configuration
    cat > "${LDAP_SHARE_DIR}/ppolicy_create_configuration.ldif" << EOF
dn: olcOverlay={0}ppolicy,olcDatabase={2}mdb,cn=config
objectClass: olcOverlayConfig
objectClass: olcPPolicyConfig
olcOverlay: {0}ppolicy
EOF
    debug_execute ldapadd -Q -Y EXTERNAL -H "ldapi:///" -f "${LDAP_SHARE_DIR}/ppolicy_create_configuration.ldif"
    # enable ppolicy_hash_cleartext
    if is_boolean_yes "$LDAP_PPOLICY_HASH_CLEARTEXT"; then
        info "Enabling ppolicy_hash_cleartext"
        cat > "${LDAP_SHARE_DIR}/ppolicy_configuration_hash_cleartext.ldif" << EOF
dn: olcOverlay={0}ppolicy,olcDatabase={2}mdb,cn=config
changetype: modify
add: olcPPolicyHashCleartext
olcPPolicyHashCleartext: TRUE
EOF
    debug_execute ldapmodify -Q -Y EXTERNAL -H "ldapi:///" -f "${LDAP_SHARE_DIR}/ppolicy_configuration_hash_cleartext.ldif"
    fi
    # enable ppolicy_use_lockout
    if is_boolean_yes "$LDAP_PPOLICY_USE_LOCKOUT"; then
        info "Enabling ppolicy_use_lockout"
        cat > "${LDAP_SHARE_DIR}/ppolicy_configuration_use_lockout.ldif" << EOF
dn: olcOverlay={0}ppolicy,olcDatabase={2}mdb,cn=config
changetype: modify
add: olcPPolicyUseLockout
olcPPolicyUseLockout: TRUE
EOF
        debug_execute ldapmodify -Q -Y EXTERNAL -H "ldapi:///" -f "${LDAP_SHARE_DIR}/ppolicy_configuration_use_lockout.ldif"
    fi
}
```

**Comment by jp-gouin** [comment]
You should add them in customSchema

**Comment by avodapalli2** [comment]
@jp-gouin I have added that in custom schema and the error related to olcPPolicyDefault  but got new error as 
`missing or invalid at 'pwdPolicySubentry', no policy will be applied!`
And still same issue with 'attribute 'pwmData' not allowed'

**Comment by jp-gouin** [comment]
Can you provide me the log of the first startup of `openldap-0` ? and what are the ldif files you try to apply (and schema) 

Thanks

**Comment by avodapalli2** [comment]
Here are my helm values file which contains ldiff and schemas and the logs from openldap-0 pod
[ldap-logs-latest.txt](https://github.com/user-attachments/files/16335986/ldap-logs-latest.txt)
[ldap-values.txt](https://github.com/user-attachments/files/16335988/ldap-values.txt)

**Comment by avodapalli2** [comment]
Finally PWM integration worked i had to move my acl part also in schemas with specific attributes instead of * like this


    dn: olcDatabase={2}mdb,cn=config
    changetype: modify
    replace: olcAccess
    olcAccess: {0}to attrs=jpegPhoto,userPassword,shadowLastChange,pwmResponseSet
       by self write
       by dn="cn=admin,dc=skat-classic,dc=dxc,dc=com" write
       by anonymous auth
       by * none
    olcAccess: {1}to *
       by self write
       by dn="cn=admin,dc=skat-classic,dc=dxc,dc=com" write
       by dn="cn=readonly,dc=skat-classic,dc=dxc,dc=com" read
       by * none

**Comment by jp-gouin** [comment]
Glad to hear it, would you like to describe your use case in the `advanced_examples` folder ? 

If you prefer you can provide me your values file and I'll do it

**Comment by avodapalli2** [comment]
@jp-gouin Sure , as you told previously that   password policy is loaded after the schemas were added.  schemas are loaded after the custom acls are executed and those pwm attributes which i provided with schemas were not available for the custom acls.  So the order of the schemas, acl and ldiff is somewhat not correct. So I moved my acl in schemas after loading the attributes from schemas. Here is my latest values file which worked with pwm intergration. I changed my values file with example domain instead of my own domain. 
[final-values.txt](https://github.com/user-attachments/files/16348022/final-values.txt)

**Comment by tiborauer** [comment]
Hi @avodapalli2,

Just out of curiosity: Why did you go for the manual approach rather than using the env var?

More importantly: Did you manage to configure ppolicy with more than 1 replica?

Also to @jp-gouin,
I tested enabling ppolicy through the env var, and I has no issue with the first but with the second replica stating _unsupported operation "1.3.6.1.4.1.1466.20037"_

**Comment by tiborauer** [comment]
Further info:
I found the following in the logs of the second replica:

> 693832fc.051a684b 0x7edbf11fc6c0 module_load: (ppolicy.so) already loaded
> 693832fc.051d11e5 0x7edbf11fc6c0 olcModuleLoad: value #0: <olcModuleLoad> handler exited with 1!
> 693832fc.051f4659 0x7edbf11fc6c0 conn=1023 op=1 RESULT tag=105 err=80 qtime=0.000448 etime=0.788777 text=<olcModuleLoad> handler exited with 1
> ldap_add: Other (e.g., implementation specific) error (80)
> 	additional info: <olcModuleLoad> handler exited with 1

**Comment by tiborauer** [comment]
I also found a potential solution, which requires a fix on the container. Basically, the module MUST be loaded only on the main replica but not on the others. I'll submit a PR to the container repo.

**Comment by aparnavodapalli** [comment]
@tiborauer I am using only one replica, as i was not sure if it can support more than one replica, and which env var you are talking here

**Comment by tiborauer** [comment]
`LDAP_CONFIGURE_PPOLICY`, as specified [here](https://github.com/[jp-gouin/openldap-container](https://github.com/jp-gouin/openldap-container?tab=readme-ov-file#configuration)?tab=readme-ov-file#configuration).
