### ISSUE TITLE
Add support for user password rotation

### ISSUE THREAD

**Issue by gberche-orange** [jp-gouin/helm-openldap#188]
**Is your feature request related to a problem? Please describe.**

Changes to `userPasswords` are ignored (only picked up on first start)

**Describe the solution you'd like**

changes to userPasswords are applied to the container

I believe this is an upstream limitation of the bitnami image similar to https://github.com/bitnami/containers/issues/44545

The second start shows the following traces indicating "Using persisted data" and not proceeding with existing configuration
```
Defaulted container "openldap-stack-ha" out of: openldap-stack-ha, init-schema (init), init-tls-secret (init)                                                                                                      
 10:58:25.14 INFO  ==> ** Starting LDAP setup **                                                         
 10:58:25.24 INFO  ==> Validating settings in LDAP_* env vars                                            
 10:58:25.26 INFO  ==> Initializing OpenLDAP...                                                                                                                                                                    
 10:58:25.26 DEBUG ==> Ensuring expected directories/files exist...                                                                                                                                                
 10:58:25.29 INFO  ==> Using persisted data                                                                                                                                                                        
 10:58:25.30 INFO  ==> ** LDAP setup finished! **                                                                                                                                                                  
```

https://github.com/bitnami/containers/blob/54360af174f405dd7770a867ea880e8469639f3b/bitnami/openldap/2.6/debian-12/rootfs/opt/bitnami/scripts/openldap/setup.sh#L18-L27
https://github.com/bitnami/containers/blob/54360af174f405dd7770a867ea880e8469639f3b/bitnami/openldap/2.6/debian-12/rootfs/opt/bitnami/scripts/libopenldap.sh#L611-L619
https://github.com/bitnami/containers/blob/54360af174f405dd7770a867ea880e8469639f3b/bitnami/openldap/2.6/debian-12/rootfs/opt/bitnami/scripts/libopenldap.sh#L592-L600

**Describe alternatives you've considered**

Rotating user passwords using ldap cli

**Additional context**

Thanks again for the great work on this project !

**Comment by jp-gouin** [comment]
It's in my fork https://github.com/jp-gouin/containers/tree/main/bitnami/openldap 

It's not the plan to maintain a fork however one mandatory PR that I submitted has been reverted. I need to find an alternative to the PR to use the upstream one again.
