### ISSUE TITLE
Not able to port-forward port 389 

### ISSUE THREAD

**Issue by mluyo3414** [jp-gouin/helm-openldap#19]
**Describe the bug**
Not able to port-forward port 389 

**To Reproduce**

`kubectl port-forward openldap-phpldapadmin-cfcc57847-9d7bm 3890:389 -n tools`

Error:

```
Forwarding from 127.0.0.1:3890 -> 389
Forwarding from [::1]:3890 -> 389
Handling connection for 3890
E0316 18:59:44.217607   65888 portforward.go:400] an error occurred forwarding 3890 -> 389: error forwarding port 389 to pod 180293b77f6fd52a2a7ba76457212268e23f2a612f5670073fda231d373c978a, uid : failed to execute portforward in network namespace "/var/run/netns/cni-e814d0a1-605e-a6c4-9158-9cf87936d975": failed to dial 389: dial tcp4 127.0.0.1:389: connect: connection refused
```

**Expected behavior**
Able to port-forward port 389 to be able to connect from other external `machines` 

**Context**

```
kind v0.10.0 go1.15.7 darwin/amd64
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-21T01:11:42Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by jp-gouin** [comment]
Hi, 

I think you are trying to forward the port 389 of phpldapadmin instead of openldap database .
Phpldapadmin expose the port 80 since it’s a webUi and openldap pod is exposing port 389 and 636 for ldap and ldaps.

**Comment by mluyo3414** [comment]
Looks like that was it! Thanks! I connected with

`kubectl port-forward my-release-openldap-stack-ha-0 3890:389`

`ldapsearch -x -H ldap://localhost:3890 -b dc=example,dc=org -D "cn=admin,dc=example,dc=org" -w XXXXX`

Thanks!
