### ISSUE TITLE
no serverID / URL match found. Check slapd -h arguments.

### ISSUE THREAD

**Issue by guolinghong** [jp-gouin/helm-openldap#193]
I encountered an issue while deploying OpenLDAP in k8s, which prevented it from starting.
The logs of the pod are like the following content, and I cannot only obtain the error reason and solution from the logs.
May I ask how I should handle this issue
`
openldap GID/UID
-------------------------------------
User uid: 911
User gid: 911
uid/gid changed: false
-------------------------------------
updating file uid/gid ownership
Check previous TLS certificates...
Hi! I'm ssl-helper, what button should i press ?
cfssl-helper is launched, everybody on the floor!
Files /container/service/slapd/assets/certs/tls.crt and /container/service/slapd/assets/certs/tls.key exists, fix files permissions
Start OpenLDAP...
Waiting for OpenLDAP to start...
66d0261c @(#) $OpenLDAP: slapd 2.4.50+dfsg-1~bpo10+1 (May  4 2020 05:25:06) $
	Debian OpenLDAP Maintainers <pkg-openldap-devel@lists.alioth.debian.org>
66d0261c read_config: no serverID / URL match found. Check slapd -h arguments.
66d0261c slapd stopped.
66d0261c connections_destroy: nothing to destroy
`

**Comment by jp-gouin** [comment]
Hi, @guolinghong 

Sorry for the late reply. 

If you still encounter the issue, please provide me your `values` 

Can you also post the log of the first start of `openldap-0` 

**Hint** : you can use kubectl logs --previous ... to get the logs of the previous pod in case of restart
