### ISSUE TITLE
4.x 'Extra schema cannot be added/modified' - why

### ISSUE THREAD

**Issue by EugenMayer** [jp-gouin/helm-openldap#202]
Thanks for switching to bitname openldap.

I would consider going back from my fork https://github.com/EugenMayer/helm-openldap to you again, but this very detail bothers me.

As you can see in https://github.com/EugenMayer/docker-image-ldapexample/blob/main/docker-compose.yml#L12 one can perfectly add new schemas (especially important for member of) by adding ldifs into /schema

Is there any particular reason why you opted out to support that?

**Comment by jp-gouin** [comment]
Hi @EugenMayer ,

Extra schema are supported , you can see how it can be leverage in [advanced examples](https://github.com/jp-gouin/helm-openldap/tree/master/advanced_examples). 

It also heavily tested in the CI where you can find more examples -> [CI values](https://github.com/jp-gouin/helm-openldap/blob/master/.bin/myval.yaml)

**Comment by EugenMayer** [comment]
Thanks, Great! Is the README wrong than or did i just missunderstand it?

**Comment by jp-gouin** [comment]
yeah I just updated it to reflect the current state of the chart.

When 4.0.0 came out , extra schema was not supported but it was fixed in 4.1.x 

I'm closing the issue , feel free to re-open it if you need more clarity
