### ISSUE TITLE
Problems with Apache Ldap Studio (bug)

### ISSUE THREAD

**Issue by EugenMayer** [jp-gouin/helm-openldap#212]
Right away, i do not think this is related to this chart in a direct way, since i can reproduce the issue with my docker-compose base boilerplate too (https://github.com/EugenMayer/docker-image-ldapexample/tree/main)

In both case, i can see that TLS/SSL is working (testing via network check in apache ldap studio). In the chart i leave the ports to how they are, in my boilerplate i map them to https://github.com/EugenMayer/docker-image-ldapexample/blob/main/docker-compose.yml#L17 (also tried to map them to 1389 / 1636 to see if the symmetry is an issue).

So in both cases, i fail to authenticate, because it creates a timeout on the check. 

```bash
ldap1  | 671b7f53.2e5425a2 0x7fc27b9136c0 conn=1000 fd=14 ACCEPT from IP=172.31.0.1:36694 (IP=0.0.0.0:1636)
ldap1  | 671b7f53.310a8d76 0x7fc27b9136c0 conn=1000 fd=14 TLS established tls_ssf=256 ssf=256 tls_proto=TLSv1.3 tls_cipher=TLS_AES_256_GCM_SHA384
ldap1  | 671b7f53.310cb67f 0x7fc27b9136c0 conn=1000 op=0 BIND dn="cn=admin,dc=kontextwork,dc=com" method=128
ldap1  | 671b7f53.310d95cf 0x7fc27b9136c0 conn=1000 op=0 RESULT tag=97 err=49 qtime=0.000007 etime=0.000111 text=
ldap1  | 671b7f58.2ee67601 0x7fc27b9136c0 conn=1000 fd=14 closed (connection lost)
```

Has anybody managed to get this running at all? I had no issues with osixia so i'am wondering. Tried. 2.5.18 too, same result. Tried to configure with

```yaml
     LDAP_ENABLE_PROXYPROTO: "yes"
     LDAP_PROXYPROTO_PORT_NUMBER: 30389
     LDAP_PROXYPROTO_LDAPS_PORT_NUMBER: 30636
```

but same timeout. I can connect without using TLS/SSL on those ports without any issues at the same time. 

Thanks for any hint / sharing your experience

**Comment by EugenMayer** [comment]
Intersting, using the cli with

tls
```bash
ldapsearch -x -ZZ -H ldap://localhost:30389 -b "dc=example,dc=org" -D "cn=admin,dc=example,dc=org" -wadmin
```

and
ssl
```bash
ldapsearch -x -H ldaps://localhost:30636 -b "dc=example,dc=org" -D "cn=admin,dc=example,dc=org" -wadmin
```

both work - while apache ldap studio just gets stuck.

Using osixia with a self signed certificate does work with apacha ldap studio via TLS and SSL. I'am not sure this is due to ciphers that have been blocked in newer openldap or whatever

**Comment by EugenMayer** [comment]
Today i tried the entire setup with my official cert - apache ldap studio still stuck on the authentication step while the certificate does no longer need an exception and it still does not work.

So this stays an issue with bitnami/openldap, but not with osixia. 

Anybody has a productuion bitnami/openldap with tls/ssl which does work with apache ldap studio?

**Comment by EugenMayer** [comment]
After more testing, i found out that it is an apache-ldap-studio bug.

When you setup a connection, and try to verify the crentials while having TLS or SSL active, it will get stuck. When you simply save the connection (nevertheless) and then try to connect, it simply works.

Even though this behaves differently with osixia, i assume apache-ldap-studio is not maintained enough to go with all the things that have thanged, the last release is years ago.

For me, this is at least good enough, @jp-gouin let me know if we should link this issue somewhere or simply close it.

**Comment by jp-gouin** [comment]
Sounds good, thank you for the investigation!

**Comment by EugenMayer** [comment]
The reason this does not happen with osixia is, that osixia uses openldap that is as old that the max TLS version is 1.2, which is the one ALS works with. The newer bitnami image uses a proper newer openldap which enabled TLS 1.3, which ALS will then use (and fail)

**Comment by EugenMayer** [comment]
Closing this issue since it is not related to the chart nor the bitname image, but rather to apache ldap studio. Keeping it as a reference
