### ISSUE TITLE
existingClaim ?

### ISSUE THREAD

**Issue by m4dm4rtig4n** [jp-gouin/helm-openldap#28]
Hello,

I want use longhorn for persistantdata, but i don't find where i can set existingClaim.
Am I missing a few things ?

**Comment by jp-gouin** [comment]
Hi, 

Right now the chart does not support existing claim.

PR are welcome :)

**Comment by m4dm4rtig4n** [comment]
=> https://github.com/jp-gouin/helm-openldap/pull/29

**Comment by jp-gouin** [comment]
Closed with #29 and #30
