### ISSUE TITLE
Trouble getting phpadmin connection to work

### ISSUE THREAD

**Issue by pat-s** [jp-gouin/helm-openldap#40]
Hi,

thanks for this helm chart and the work which went into it!

We've been running a phpadmin & LDAP containers for a while and would like to switch to helm now.

We've read the instructions how to get phpadmin working but I cannot get the connection between phpldapadmin and ldap to work.
Here's how we do it currently:

```tf
set {
    name  = "phpldapadmin.env.PHPLDAPADMIN_LDAP_HOSTS"
    value = "<namespace>.<subdomain>.example.org"
}

set {
    name  = "phpldapadmin.ingress.hosts[0]"
    value = "<subdomain>.example.org"
}

set {
    name  = "adminPassword"
    value = var.OPENLDAP_PASS
}

set {
    name  = "phpldapadmin.ingress.enabled"
    value = true
}

```

We can reach the service via https://<subdomain>.example.org.
When logging in using the `admin` user (is that correct?) and the password which is passed as a secret, we see

```
Unable to connect to LDAP server openldap
--
Error: Can't contact LDAP server (-1) for user

```

So it seems something is still borked with the connection between phpldapadmin pod to the ldap pods. Is there a way in k8s to check which value would be the correct one for `PHPLDAPADMIN_LDAP_HOSTS`? Or is there something else wrong in our setup?

**Comment by pat-s** [comment]
Got it...

Turns out one does not need to set `phpldapadmin.env.PHPLDAPADMIN_LDAP_HOSTS` necessarily.

I just had the login user wrong - I needed to use `cn=admin,dc=<org>,dc=<domain>` with the PW set in `adminPassword` and it worked.

**Comment by fabian-milea** [comment]
Hi Pat-s, I think I have the same issue. I have installed the cluster but from the phpadminldap web interface, when I try to login with admin and the password generate by:  `kubectl get secret --namespace ldap gdpldap-openldap-stack-ha -o jsonpath="{.data.LDAP_ADMIN_PASSWORD}" | base64 --decode; echo`

where do you use: `cn=admin,dc=<org>,dc=<domain>`?

**Comment by pat-s** [comment]
As the username in the login field.

**Comment by fabian-milea** [comment]
Thanks, in may case is still not working... I have a different issue... probably the connection between phpldapadmin and openldap...

**Comment by pat-s** [comment]
I have only `phpldapadmin.ingress.hosts` set - no other phpldapadmin setting. AFAICS the chart automatically takes care that phpldapadmin finds the ldap pods. 

I've set `adminPassword` which is a Terraform secret in my case.
In your case I would try with a plain text PW (if that's supported) to rule out that issue and then try again.

Note that the username for phpldapadmin is really the full `cn=admin,dc=<org>,dc=<domain>` phrase.
