### ISSUE TITLE
Option to set slapd log level

### ISSUE THREAD

**Issue by asavchkov** [jp-gouin/helm-openldap#43]
I want to set the log level of slapd and I can't do it. The underlying image gets the log level from the LDAP_LOG_LEVEL environment variable but there doesn't seem to be a way to pass its value through the Helm chart.

I would like to be able to set the container LDAP_LOG_LEVEL, either through a dedicated Helm chart variable or through a custom envvar file mounted on the container `/container/environment/01-custom` dir as the image README suggests.

**Comment by jp-gouin** [comment]
Hello @asavchkov 

there are multiple ways to configure the log level.
https://github.com/jp-gouin/helm-openldap/blob/2607589f86ee96adae5aff285af447aa3d159a77/values.yaml#L35 set the log level of the container .

And you also can add the environment variable directly under the `env` section here https://github.com/jp-gouin/helm-openldap/blob/2607589f86ee96adae5aff285af447aa3d159a77/values.yaml#L85

**Comment by asavchkov** [comment]
Indeed, setting LDAP_LOG_LEVEL in values.yaml under the `env:` section works, have overlooked this option, closing the issue.
