### ISSUE TITLE
Any particular reason you are no longer updated on artfacthub

### ISSUE THREAD

**Issue by EugenMayer** [jp-gouin/helm-openldap#51]
Is there any reason you are no longer updated on https://artifacthub.io/packages/helm/helm-openldap/openldap ?

I find the platform fairly handy to follow / watch releases and search for existing charts across chart repositories. 

Any way to help you on board it once again or is it by design and you do no like that to happen? Happy to hear your thoughts on that. Thanks!

**Comment by jp-gouin** [comment]
Hi @EugenMayer 

I changed the name of the chart some time ago to better reflect the chart.
https://artifacthub.io/packages/helm/helm-openldap/openldap-stack-ha
