### ISSUE TITLE
OpenLDAP does not deploy successfully with default values

### ISSUE THREAD

**Issue by tim-beatson** [jp-gouin/helm-openldap#61]
**Describe the bug**
When installing the chart with the default values, an error is shown when describing the openldap stateful set which suggests a secret is missing and no openldap pods are created.

**To Reproduce**
1. helm repo add helm-openldap https://jp-gouin.github.io/helm-openldap/ 
2. helm install openldap helm-openldap/openldap-stack-ha 
3. kubectl describe statefulset openldap
4. Warning is shown detailing pods cannot be created as a secret required for a volume is not present. Pods are created for phpldapadmin and ltb-passwd but not for openldap.

**Expected behavior**
Three ready and functional openldap pods resulting in a working deployment of OpenLDAP.

**Screenshots**
Warning  FailedCreate      6s (x6 over 57s)  statefulset-controller  create Pod openldap-0 in StatefulSet openldap failed error: Pod "openldap-0" is invalid: [spec.volumes[1].secret.secretName: Required value, spec.initContainers[0].volumeMounts[1].name: Not found: "secret-certs"]

**Comment by tim-beatson** [comment]
@jp-gouin, please could you re-open this issue?
Using the values you suggest in #60, the first replica starts successfully but the other two fail to start, with this observed in the logs each time they try:
`***  INFO   | 2022-05-26 15:10:27 | CONTAINER_LOG_LEVEL = 3 (info)
***  INFO   | 2022-05-26 15:10:27 | Search service in CONTAINER_SERVICE_DIR = /container/service :
***  INFO   | 2022-05-26 15:10:27 | link /container/service/:ssl-tools/startup.sh to /container/run/startup/:ssl-tools
***  INFO   | 2022-05-26 15:10:27 | link /container/service/slapd/startup.sh to /container/run/startup/slapd
***  INFO   | 2022-05-26 15:10:27 | link /container/service/slapd/process.sh to /container/run/process/slapd/run
***  INFO   | 2022-05-26 15:10:27 | Environment files will be proccessed in this order : 
Caution: previously defined variables will not be overriden.
/container/environment/99-default/default.startup.yaml
/container/environment/99-default/default.yaml

To see how this files are processed and environment variables values,
run this container with '--loglevel debug'
***  INFO   | 2022-05-26 15:10:27 | Running /container/run/startup/:ssl-tools...
***  INFO   | 2022-05-26 15:10:27 | Running /container/run/startup/slapd...
***  INFO   | 2022-05-26 15:10:27 | openldap user and group adjustments
***  INFO   | 2022-05-26 15:10:27 | get current openldap uid/gid info inside container
***  INFO   | 2022-05-26 15:10:27 | -------------------------------------
***  INFO   | 2022-05-26 15:10:27 | openldap GID/UID
***  INFO   | 2022-05-26 15:10:27 | -------------------------------------
***  INFO   | 2022-05-26 15:10:27 | User uid: 911
***  INFO   | 2022-05-26 15:10:27 | User gid: 911
***  INFO   | 2022-05-26 15:10:27 | uid/gid changed: false
***  INFO   | 2022-05-26 15:10:27 | -------------------------------------
***  INFO   | 2022-05-26 15:10:27 | updating file uid/gid ownership
***  INFO   | 2022-05-26 15:10:27 | Start OpenLDAP...
***  INFO   | 2022-05-26 15:10:27 | Waiting for OpenLDAP to start...
***  INFO   | 2022-05-26 15:10:27 | Add TLS config...
***  INFO   | 2022-05-26 15:12:38 | Add replication config...
***  INFO   | 2022-05-26 15:21:24 | Stop OpenLDAP...
*** WARNING | 2022-05-26 15:22:55 | An error occurred. Aborting.
***  INFO   | 2022-05-26 15:22:55 | Shutting down /container/run/startup/slapd (PID 11)...
*** WARNING | 2022-05-26 15:22:55 | Init system aborted.
***  INFO   | 2022-05-26 15:22:55 | Killing all processes...
*** WARNING | 2022-05-26 15:23:25 | Not all processes have exited in time. Forcing them to exit.`
This is followed by the pod restarting.

**Comment by jp-gouin** [comment]
Is it a fresh instance ? Since it's a statefullset if you have redeploy without deleting prior the namespace you could end up with existing volume 
That could be the cause of your issue

**Comment by jp-gouin** [comment]
I cannot reproduce your issue.
Could you describe your environment ? (cloud provider, storage provider...)

Also could you turn on the `debug` log -> `logLevel: debug`
