### ISSUE TITLE
ldap-ltb-passwd CrashLoopBackOff with default values

### ISSUE THREAD

**Issue by AustralEpitech** [jp-gouin/helm-openldap#65]
**Describe the bug**
ldap-ltb-passwd keeps crashing because of nginx missing file

**To reproduce**
1. helm install my-release helm-openldap/openldap-stack-ha

**Expected behavior**
```console
$ kubectl get pod | grep ldap-ltb-passwd
ldap-ltb-passwd-5494c456c-nkhf4      1/1     Running   0          1m
```

**Screenshots**
```console
$ kubectl logs deployment/ldap-ltb-passwd
2022-06-24.09:24:20 [STARTING] ** [nginx] [24] Starting nginx 1.23.0
nginx: [emerg] open() "/etc/nginx/nginx.conf.d/php-fpm.conf" failed (2: No such file or directory) in /etc/nginx/sites.available/ssp.conf:11
```

**Comment by DmitryZakharov** [comment]
the problem is the image in  the deployment fasttrack-ldap-ltb-passwd
which uses Image tiredofit/self-service-password:latest

the latest image is not compatible. Manually editing deployment and setting image to 5.2.1 fixes the problem.

**Comment by DmitryZakharov** [comment]
add following lines to values.yaml as the workaround:

```
ltb-passwd:
  image:
    tag: 5.2.1
```

**Comment by AustralEpitech** [comment]
Works perfectly, thank you !

**Comment by DmitryZakharov** [comment]
> Works perfectly, thank you !

why did you close the ticket ? I have just provided a workaround and it must be properly fixed.

**Comment by jp-gouin** [comment]
I reopen it to provide in the next update the fix for the new version of `tiredofit/self-service-password:latest`
-> It require to push an additional fine in the container to init `nginx`
