### ISSUE TITLE
Password with special characters is not supported

### ISSUE THREAD

**Issue by AustralEpitech** [jp-gouin/helm-openldap#70]
**To Reproduce**
1. wget https://github.com/jp-gouin/helm-openldap/raw/master/values.yaml
2. edit adminPassword (I belive it is the '/' that is not supported because of sed)
3. helm repo add helm-openldap https://jp-gouin.github.io/helm-openldap/
4. helm install my-release helm-openldap/openldap-stack-ha

**Expected behavior**
Everything works

**Screenshots**
```console
$ kubectl get pods
NAME                                 READY   STATUS             RESTARTS      AGE
ldap-phpldapadmin-5cbd44ffc5-c55t6   1/1     Running            0             2m20s
ldap-0                               0/1     CrashLoopBackOff   4 (51s ago)   2m20s
```

**Additional context**
There is this error in the logs:
```console
$ kubectl logs ldap-0
sed: -e expression #1, char 30: unknown option to `s'
```

**Comment by jp-gouin** [comment]
Nice catch ! 
have you try to escape the `/` ?

if that works I’ll update the readme with a warning and the `values.yaml`

In another milestone it could be possible to include some magic in the helper to escape automatically the character

**Comment by AustralEpitech** [comment]
When I put `test/\`, I get the error `Error: INSTALLATION FAILED: failed to parse /home/ange/dev/ldap/helm-openldap.yaml: error converting YAML to JSON: yaml: line 9: found unknown escape character`
But with `test\\/`, it works (but the password will contain `\` as a character)
