### ISSUE TITLE
ltb-passwd default to ldaps. there should be an option to select ldap or ldaps

### ISSUE THREAD

**Issue by joshiparth1000** [jp-gouin/helm-openldap#72]
**Is your feature request related to a problem? Please describe.**
I am exposing ldap within the cluster and dont want ssl. the ltb-passwd chart default to using ldaps.

**Describe the solution you'd like**
There should be option to select ldap or ldaps port

**Describe alternatives you've considered**
Creating a separate chart for ltb-passwd

**Additional context**

**Comment by jp-gouin** [comment]
Hey,

I'm not a fan of exposing ldap instead of ldaps.

But if you need to , you can add a parameter ´insecure´ in the ssp-pd chart to use ldap instead of ldaps and add it to the values then it'll be available in the main chart
