### ISSUE TITLE
podAnnotations unused

### ISSUE THREAD

**Issue by roertel** [jp-gouin/helm-openldap#76]
**Describe the bug**
The `podAnnotations` setting in `values.yaml` does not get applied to the OpenLDAP pods. 

**To Reproduce**
1. Install the helm chart setting values for podAnnotations: `--set podAnnotations=name=value`
2. Verify the annotations for the `openldap-stack-ha-0` pod
3. `name=value` does not appear in the list of annotations

**Expected behavior**
Annotations in the `podAnnotations` field are expected to be applied to the openldap-stack-ha-* pods, per the documentation. 

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: NA
 - Browser NA
 - Version NA

**Smartphone (please complete the following information):**
 - Device: NA
 - OS: NA
 - Browser NA
 - Version NA

**Additional context**
NA

**Comment by roertel** [comment]
I have a 3-line tested patch for this and would be happy to submit a PR. Please advise.

**Comment by jp-gouin** [comment]
Hi @roertel ,
Sure please submit the PR !
