### ISSUE TITLE
Backup and Restore

### ISSUE THREAD

**Issue by NeelavaChatterjee** [jp-gouin/helm-openldap#82]
I was able to get the openldap backup to work using slapd service but the restore part didn't seem to work so do we have any workaround for backup and restore, as it is a very important feature.

Found a issue #42 related to this which seems to have been marked won't fix and closed.

**Comment by jp-gouin** [comment]
Hi , 
I think the right approach is to use `ldapsearch` and query specifically the subtree you need to backup and discard internal data coming from `config` ... 

Then you just need to apply the ldif using `ldapadd` in a fresh instance. 

A more global approach would be to use a tool like [Velero](https://velero.io/) and snapshot all volumes and then restore them before installing a fresh instance of Openldap. The sts should use automatically the existing volume using the PVC

I'm planning to include a feature to snapshot and restore from a S3 , but right now I can't tell you when this will be available

**Comment by NeelavaChatterjee** [comment]
Thanks
