### ISSUE TITLE
rootless securityContext

### ISSUE THREAD

**Issue by itmwiw** [jp-gouin/helm-openldap#83]
Hello,
First of all, thanks for the effort. Keep up the good work!
My issue is that I can't run openldap in rootless pod. I found out this issue in osixia github repository https://github.com/osixia/docker-openldap/issues/544
However, as this chart's values offers runAsNonRoot attribute, I was wondering if there's some workaround to make it work.
Thanks in advance

**Comment by jp-gouin** [comment]
Hi @itmwiw 
Thanks :) 
I was working on the chart to switch the base image to a new Openldap (maintained by Bitnami)

Check out the new version `v4.0.0` as I think  this automatically resolves your issue.

**Comment by asatsi** [comment]
> Hi @itmwiw Thanks :) I was working on the chart to switch the base image to a new Openldap (maintained by Bitnami)
> 
> Check out the new version `v4.0.0` as I think this automatically resolves your issue.

@jp-gouin - new version v4.0.0 of which particular image are you referring here? I am also trying to run openldap as non-root container.

**Comment by itmwiw** [comment]
> Hi @itmwiw Thanks :) I was working on the chart to switch the base image to a new Openldap (maintained by Bitnami)
> 
> Check out the new version `v4.0.0` as I think this automatically resolves your issue.

Great! I'll try it out. Thanks

**Comment by itmwiw** [comment]
I created a pull request so that initiating certificates works with openshift's restricted scc.
I also have a question regarding phpldapadmin and rootless mode. Does it work for you or should I change the osixia docker image?
