### ISSUE TITLE
Possibility to set resources for the default init container

### ISSUE THREAD

**Issue by jpex34** [jp-gouin/helm-openldap#86]
**Is your feature request related to a problem? Please describe.**
With the actual chart it's not possible to set resources for the default init container "init-chmod-secret". In order to set them I need to download the chart and modify the stafullset.yaml template directly

**Describe the solution you'd like**

Possibility to set resources from the values.yaml file

**Describe alternatives you've considered**

Download the chart direcly and modify the template but it's not a very suitable workarround

**Comment by jp-gouin** [comment]
Hi @jpex34 , what is your use case ?
The init container is short live and does not perform high operation , did you encounter any issue ? 

Regardless PR are more than welcome 🤗
