### ISSUE TITLE
Pod cannot be created when using existing claim

### ISSUE THREAD

**Issue by zirrok80** [jp-gouin/helm-openldap#88]
Hi. When using persistence.existingClaim the pod cannot be created due to the error "create Pod openldap-0 in StatefulSet openldap failed error: Pod "openldap-0" is invalid: spec.volumes[10].name: Duplicate value: "data"". I think its because of the if/else statement in the statefulset.yaml in line 294/317. When an existing claim is defined the emptyDir data is used. Maybe the intention of the else was to check persistence.enabled?

Best regards,
Björn

**Comment by jp-gouin** [comment]
Hi @zirrok80 , thanks for the issue

I’ll do some testing but you are more likely right the else need to verify `persistence.enabled `

**Comment by jp-gouin** [comment]
fixed in the last version `4.1.0`
