### ISSUE TITLE
ARM64 image

### ISSUE THREAD

**Issue by Evantage-WS** [jp-gouin/helm-openldap#93]
Hi, I am running K8s on my Macos/M1 and I want to use this helm chart, is it possible that you add an ARM64 version?

I found this repo for bitnami openldap on arm64: https://github.com/Marsu31/bitnami-openldap-arm64/blob/main/bitnami/openldap/2.6/debian-11/Dockerfile

**Comment by jp-gouin** [comment]
Hi @Evantage-WS , 
if this image is published on Dockerhub or another container repository, you can update the values.yaml with `image.repository` pointing to your ARM image.

**Comment by Evantage-WS** [comment]
Hi @jp-gouin,

Thanks for your answer.

Yes, already tried that, I get the pod up and running, but a lot of network errors in the log, so I stopped testing.

**Comment by jp-gouin** [comment]
Ok might have been errors related to config user not having the proper name 
PR is in progress to resolve that
However it should not impact the replication and the run of container 

What exactly were your errors ?

**Comment by Evantage-WS** [comment]
Sorry, I already uninstalled it all. The error was somehting like setting up a connection and immediatly there was a reset. The was no ldap client using that server or even installed. The container was up and running, but this was shown in the log.

**Comment by SamuelLHuber** [comment]
@Evantage-WS the bitnami docker image used as base of this chart seems to have an ARM64 image now listed on dockerhub.
