### ISSUE TITLE
change base dn from dc to o,c

### ISSUE THREAD

**Issue by ljjolic99** [jp-gouin/helm-openldap#96]
we need to change the base dn. Our dn is based on ou=xxx,o=yy,c=ca instead of dc=xxx,dc=yyy, how do we go about that

**Comment by jp-gouin** [comment]
Hi @ljjolic99 

Today it's not possible , but to support it it require minimal development 
Adding a variable in the values to allow override of the ldap domain and use it in the helper when defining the global.baseDomain variable 

Would you try to submit a PR ?

**Comment by jp-gouin** [comment]
fixed in the last version `4.1.0` `global.ldapDomain` can either be explicit `ou=xxx,o=yy,c=ca` or domain based `example.org` which will be translated to `dc=example,dc=org`

**Comment by ljjolic99** [comment]
so i got your latest master and helm install. I can login with "cn=admin,ou=myOrg,o=gc,c=ca" but the base DN is not recognize by openldap.

phpadminldap gives the "This base cannot be created with PLA." error 

my values.yaml:

 #imagePullSecrets: [""]
  ## ldapDomain , can be explicit (e.g dc=toto,c=ca) or domain based (e.g example.com)
  ldapDomain: "ou=myOrg,o=gc,c=ca"
  # Specifies an existing secret to be used for admin and config user passwords. The expected key are LDAP_ADMIN_PASSWORD and LDAP_CONFIG_ADMIN_PASSWORD.
  # existingSecret: ""
  ## Default Passwords to use, stored as a secret. Not used if existingSecret is set.
  adminPassword:  adminPassword
  configPassword: adminPassword

**Comment by jp-gouin** [comment]
Release will be out in the couple of minute, sorry about that
